//modals
export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";

//notes
export const FETCH_NOTES_REQUESTED = "FETCH_NOTES_REQUESTED";
export const FETCH_NOTES_SUCCESS = "FETCH_NOTES_SUCCESS";
export const FETCH_NOTES_FAILED = "FETCH_NOTES_FAILED";

export const CHANGE_NOTE = "CHANGE_NOTE";

export const FETCH_NOTE_REQUESTED = "FETCH_NOTE_REQUESTED";
export const FETCH_NOTE_SUCCESS = "FETCH_NOTE_SUCCESS";
export const FETCH_NOTE_FAILED = "FETCH_NOTE_FAILED";

export const NEW_NOTE = "NEW_NOTE";
export const SAVE_NOTE_REQUESTED = "SAVE_NOTE_REQUESTED";
export const SAVE_NOTE_SUCCESS = "SAVE_NOTE_SUCCESS";
export const SAVE_NOTE_FAILED = "SAVE_NOTE_FAILED";

export const UPDATE_NOTE_REQUESTED = "UPDATE_NOTE_REQUESTED";
export const UPDATE_NOTE_SUCCESS = "UPDATE_NOTE_SUCCESS";
export const UPDATE_NOTE_FAILED = "UPDATE_NOTE_FAILED";

export const DELETE_NOTE_REQUESTED = "DELETE_NOTE_REQUESTED";
export const DELETE_NOTE_SUCCESS = "DELETE_NOTE_SUCCESS";
export const DELETE_NOTE_FAILED = "DELETE_NOTE_FAILED";

//projects

export const FETCH_PROJECTS_REQUESTED = "FETCH_PROJECTS_REQUESTED";
export const FETCH_PROJECTS_SUCCESS = "FETCH_PROJECTS_SUCCESS";
export const FETCH_PROJECTS_FAILED = "FETCH_PROJECTS_FAILED";

export const CHANGE_PROJECT = "CHANGE_PROJECT";

export const FETCH_PROJECT_REQUESTED = "FETCH_PROJECT_REQUESTED";
export const FETCH_PROJECT_SUCCESS = "FETCH_PROJECT_SUCCESS";
export const FETCH_PROJECT_FAILED = "FETCH_PROJECT_FAILED";

export const NEW_PROJECT = "NEW_PROJECT";
export const SAVE_PROJECT_REQUESTED = "SAVE_PROJECT_REQUESTED";
export const SAVE_PROJECT_SUCCESS = "SAVE_PROJECT_SUCCESS";
export const SAVE_PROJECT_FAILED = "SAVE_PROJECT_FAILED";

export const UPDATE_PROJECT_REQUESTED = "UPDATE_PROJECT_REQUESTED";
export const UPDATE_PROJECT_SUCCESS = "UPDATE_PROJECT_SUCCESS";
export const UPDATE_PROJECT_FAILED = "UPDATE_PROJECT_FAILED";

export const DELETE_PROJECT_REQUESTED = "DELETE_PROJECT_REQUESTED";
export const DELETE_PROJECT_SUCCESS = "DELETE_PROJECT_SUCCESS";
export const DELETE_PROJECT_FAILED = "DELETE_PROJECT_FAILED";
//workitem

export const CHANGE_WORKITEM = "CHANGE_WORKITEM";
export const CLEAR_WORKITEMS = "CLEAR_WORKITEMS";

export const FETCH_WORKITEMS_REQUESTED = "FETCH_WORKITEMS_REQUESTED";
export const FETCH_WORKITEMS_SUCCESS = "FETCH_WORKITEMS_SUCCESS";
export const FETCH_WORKITEMS_FAILED = "FETCH_WORKITEMS_FAILED";

export const FETCH_WORKITEM_REQUESTED = "FETCH_WORKITEM_REQUESTED";
export const FETCH_WORKITEM_SUCCESS = "FETCH_WORKITEM_SUCCESS";
export const FETCH_WORKITEM_FAILED = "FETCH_WORKITEM_FAILED";

export const NEW_WORKITEM = "NEW_WORKITEM";
export const SAVE_WORKITEM_REQUESTED = "SAVE_WORKITEM_REQUESTED";
export const SAVE_WORKITEM_SUCCESS = "SAVE_WORKITEM_SUCCESS";
export const SAVE_WORKITEM_FAILED = "SAVE_WORKITEM_FAILED";

export const UPDATE_WORKITEM_REQUESTED = "UPDATE_WORKITEM_REQUESTED";
export const UPDATE_WORKITEM_SUCCESS = "UPDATE_WORKITEM_SUCCESS";
export const UPDATE_WORKITEM_FAILED = "UPDATE_WORKITEM_FAILED";

export const DELETE_WORKITEM_REQUESTED = "DELETE_WORKITEM_REQUESTED";
export const DELETE_WORKITEM_SUCCESS = "DELETE_WORKITEM_SUCCESS";
export const DELETE_WORKITEM_FAILED = "DELETE_WORKITEM_FAILED";

//task
export const CHANGE_TASK = "CHANGE_TASK";
export const CLEAR_TASKS = "CLEAR_TASKS";

export const FETCH_TASKS_REQUESTED = "FETCH_TASKS_REQUESTED";
export const FETCH_TASKS_SUCCESS = "FETCH_TASKS_SUCCESS";
export const FETCH_TASKS_FAILED = "FETCH_TASKS_FAILED";

export const FETCH_TASK_REQUESTED = "FETCH_TASK_REQUESTED";
export const FETCH_TASK_SUCCESS = "FETCH_TASK_SUCCESS";
export const FETCH_TASK_FAILED = "FETCH_TASK_FAILED";


export const NEW_TASK = "NEW_TASK";
export const SAVE_TASK_REQUESTED = "SAVE_TASK_REQUESTED";
export const SAVE_TASK_SUCCESS = "SAVE_TASK_SUCCESS";
export const SAVE_TASK_FAILED = "SAVE_TASK_FAILED";

export const UPDATE_TASK_REQUESTED = "UPDATE_TASK_REQUESTED";
export const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS";
export const UPDATE_TASK_FAILED = "UPDATE_TASK_FAILED";

export const DELETE_TASK_REQUESTED = "DELETE_TASK_REQUESTED";
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";
export const DELETE_TASK_FAILED = "DELETE_TASK_FAILED";


//security
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_ERRORS = "GET_ERRORS";

//user
export const FETCH_USERS_REQUESTED = "FETCH_USERS_REQUESTED";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAILED = "FETCH_USERS_FAILED";

export const CHANGE_USER = "CHANGE_USER";

export const FETCH_USER_REQUESTED = "FETCH_USER_REQUESTED";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILED = "FETCH_USER_FAILED";

export const NEW_USER = "NEW_USER";
export const SAVE_USER_REQUESTED = "SAVE_USER_REQUESTED";
export const SAVE_USER_SUCCESS = "SAVE_USER_SUCCESS";
export const SAVE_USER_FAILED = "SAVE_USER_FAILED";

export const UPDATE_USER_REQUESTED = "UPDATE_USER_REQUESTED";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILED = "UPDATE_USER_FAILED";

export const DELETE_USER_REQUESTED = "DELETE_USER_REQUESTED";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILED = "DELETE_USER_FAILED";
